// 163 ингредиента для базы MealBot
// Используется в seed.js

const ingredients = [
  // --- МОЛОЧНЫЕ ---
  { name: 'milk',             nameRu: 'Молоко',               category: 'dairy' },
  { name: 'butter',           nameRu: 'Сливочное масло',      category: 'dairy' },
  { name: 'cream',            nameRu: 'Сливки',               category: 'dairy' },
  { name: 'sour_cream',       nameRu: 'Сметана',              category: 'dairy' },
  { name: 'yogurt',           nameRu: 'Йогурт',               category: 'dairy' },
  { name: 'kefir',            nameRu: 'Кефир',                category: 'dairy' },
  { name: 'cottage_cheese',   nameRu: 'Творог',               category: 'dairy' },
  { name: 'cheese',           nameRu: 'Сыр твёрдый',          category: 'dairy' },
  { name: 'mozzarella',       nameRu: 'Моцарелла',            category: 'dairy' },
  { name: 'feta',             nameRu: 'Фета',                 category: 'dairy' },
  { name: 'parmesan',         nameRu: 'Пармезан',             category: 'dairy' },
  { name: 'cream_cheese',     nameRu: 'Сливочный сыр',        category: 'dairy' },
  { name: 'condensed_milk',   nameRu: 'Сгущённое молоко',     category: 'dairy' },
  { name: 'ryazhenka',        nameRu: 'Ряженка',              category: 'dairy' },
  { name: 'processed_cheese', nameRu: 'Плавленый сыр',        category: 'dairy' },

  // --- МЯСО ---
  { name: 'chicken_breast',   nameRu: 'Куриная грудка',       category: 'meat' },
  { name: 'chicken_thigh',    nameRu: 'Куриное бедро',        category: 'meat' },
  { name: 'chicken_whole',    nameRu: 'Курица целая',          category: 'meat' },
  { name: 'chicken_wings',    nameRu: 'Куриные крылья',       category: 'meat' },
  { name: 'ground_beef',      nameRu: 'Говяжий фарш',         category: 'meat' },
  { name: 'ground_pork',      nameRu: 'Свиной фарш',          category: 'meat' },
  { name: 'minced_meat',      nameRu: 'Смешанный фарш',       category: 'meat' },
  { name: 'beef',             nameRu: 'Говядина',             category: 'meat' },
  { name: 'pork',             nameRu: 'Свинина',              category: 'meat' },
  { name: 'turkey',           nameRu: 'Индейка',              category: 'meat' },
  { name: 'lamb',             nameRu: 'Баранина',             category: 'meat' },
  { name: 'bacon',            nameRu: 'Бекон',                category: 'meat' },
  { name: 'sausage',          nameRu: 'Колбаса',              category: 'meat' },
  { name: 'ham',              nameRu: 'Ветчина',              category: 'meat' },
  { name: 'pork_ribs',        nameRu: 'Свиные рёбра',         category: 'meat' },

  // --- РЫБА И МОРЕПРОДУКТЫ ---
  { name: 'salmon',           nameRu: 'Лосось',               category: 'fish' },
  { name: 'tuna_fresh',       nameRu: 'Тунец свежий',         category: 'fish' },
  { name: 'cod',              nameRu: 'Треска',               category: 'fish' },
  { name: 'herring',          nameRu: 'Сельдь',               category: 'fish' },
  { name: 'mackerel',         nameRu: 'Скумбрия',             category: 'fish' },
  { name: 'pollock',          nameRu: 'Минтай',               category: 'fish' },
  { name: 'pike_perch',       nameRu: 'Судак',                category: 'fish' },
  { name: 'shrimp',           nameRu: 'Креветки',             category: 'fish' },
  { name: 'squid',            nameRu: 'Кальмар',              category: 'fish' },
  { name: 'mussels',          nameRu: 'Мидии',                category: 'fish' },
  { name: 'crab_sticks',      nameRu: 'Крабовые палочки',     category: 'fish' },
  { name: 'red_caviar',       nameRu: 'Красная икра',         category: 'fish' },

  // --- ОВОЩИ ---
  { name: 'potato',           nameRu: 'Картофель',            category: 'vegetable' },
  { name: 'onion',            nameRu: 'Лук репчатый',         category: 'vegetable' },
  { name: 'garlic',           nameRu: 'Чеснок',               category: 'vegetable' },
  { name: 'carrot',           nameRu: 'Морковь',              category: 'vegetable' },
  { name: 'tomato',           nameRu: 'Помидор',              category: 'vegetable' },
  { name: 'cherry_tomato',    nameRu: 'Помидоры черри',       category: 'vegetable' },
  { name: 'cucumber',         nameRu: 'Огурец',               category: 'vegetable' },
  { name: 'bell_pepper',      nameRu: 'Болгарский перец',     category: 'vegetable' },
  { name: 'cabbage',          nameRu: 'Белокочанная капуста', category: 'vegetable' },
  { name: 'broccoli',         nameRu: 'Брокколи',             category: 'vegetable' },
  { name: 'cauliflower',      nameRu: 'Цветная капуста',      category: 'vegetable' },
  { name: 'zucchini',         nameRu: 'Кабачок',              category: 'vegetable' },
  { name: 'eggplant',         nameRu: 'Баклажан',             category: 'vegetable' },
  { name: 'beet',             nameRu: 'Свёкла',               category: 'vegetable' },
  { name: 'celery',           nameRu: 'Сельдерей',            category: 'vegetable' },
  { name: 'spinach',          nameRu: 'Шпинат',               category: 'vegetable' },
  { name: 'lettuce',          nameRu: 'Листовой салат',       category: 'vegetable' },
  { name: 'corn',             nameRu: 'Кукуруза',             category: 'vegetable' },
  { name: 'peas',             nameRu: 'Зелёный горошек',      category: 'vegetable' },
  { name: 'asparagus',        nameRu: 'Спаржа',               category: 'vegetable' },
  { name: 'leek',             nameRu: 'Лук-порей',            category: 'vegetable' },
  { name: 'radish',           nameRu: 'Редис',                category: 'vegetable' },
  { name: 'pumpkin',          nameRu: 'Тыква',                category: 'vegetable' },
  { name: 'green_onion',      nameRu: 'Зелёный лук',          category: 'vegetable' },
  { name: 'mushrooms',        nameRu: 'Шампиньоны',           category: 'vegetable' },
  { name: 'wild_mushrooms',   nameRu: 'Лесные грибы',         category: 'vegetable' },
  { name: 'sweet_potato',     nameRu: 'Батат',                category: 'vegetable' },
  { name: 'artichoke',        nameRu: 'Артишок',              category: 'vegetable' },
  { name: 'arugula',          nameRu: 'Руккола',              category: 'vegetable' },
  { name: 'chinese_cabbage',  nameRu: 'Пекинская капуста',    category: 'vegetable' },

  // --- ФРУКТЫ И ЯГОДЫ ---
  { name: 'apple',            nameRu: 'Яблоко',               category: 'fruit' },
  { name: 'banana',           nameRu: 'Банан',                category: 'fruit' },
  { name: 'orange',           nameRu: 'Апельсин',             category: 'fruit' },
  { name: 'lemon',            nameRu: 'Лимон',                category: 'fruit' },
  { name: 'lime',             nameRu: 'Лайм',                 category: 'fruit' },
  { name: 'strawberry',       nameRu: 'Клубника',             category: 'fruit' },
  { name: 'blueberry',        nameRu: 'Черника',              category: 'fruit' },
  { name: 'grape',            nameRu: 'Виноград',             category: 'fruit' },
  { name: 'pear',             nameRu: 'Груша',                category: 'fruit' },
  { name: 'peach',            nameRu: 'Персик',               category: 'fruit' },
  { name: 'mango',            nameRu: 'Манго',                category: 'fruit' },
  { name: 'pineapple',        nameRu: 'Ананас',               category: 'fruit' },
  { name: 'raspberry',        nameRu: 'Малина',               category: 'fruit' },
  { name: 'cherry',           nameRu: 'Вишня',                category: 'fruit' },
  { name: 'avocado',          nameRu: 'Авокадо',              category: 'fruit' },
  { name: 'watermelon',       nameRu: 'Арбуз',                category: 'fruit' },
  { name: 'pomegranate',      nameRu: 'Гранат',               category: 'fruit' },
  { name: 'kiwi',             nameRu: 'Киви',                 category: 'fruit' },

  // --- КРУПЫ И ЗЛАКИ ---
  { name: 'rice',             nameRu: 'Рис',                  category: 'grain' },
  { name: 'buckwheat',        nameRu: 'Гречка',               category: 'grain' },
  { name: 'oatmeal',          nameRu: 'Овсяные хлопья',       category: 'grain' },
  { name: 'pasta',            nameRu: 'Макароны',             category: 'grain' },
  { name: 'spaghetti',        nameRu: 'Спагетти',             category: 'grain' },
  { name: 'wheat_flour',      nameRu: 'Пшеничная мука',       category: 'grain' },
  { name: 'whole_wheat_flour',nameRu: 'Цельнозерновая мука',  category: 'grain' },
  { name: 'semolina',         nameRu: 'Манная крупа',         category: 'grain' },
  { name: 'barley',           nameRu: 'Перловка',             category: 'grain' },
  { name: 'millet',           nameRu: 'Пшено',                category: 'grain' },
  { name: 'couscous',         nameRu: 'Кускус',               category: 'grain' },
  { name: 'bulgur',           nameRu: 'Булгур',               category: 'grain' },
  { name: 'cornmeal',         nameRu: 'Кукурузная крупа',     category: 'grain' },
  { name: 'starch',           nameRu: 'Крахмал',              category: 'grain' },

  // --- БОБОВЫЕ ---
  { name: 'lentils',          nameRu: 'Чечевица',             category: 'legume' },
  { name: 'chickpeas',        nameRu: 'Нут',                  category: 'legume' },
  { name: 'red_beans',        nameRu: 'Красная фасоль',       category: 'legume' },
  { name: 'white_beans',      nameRu: 'Белая фасоль',         category: 'legume' },
  { name: 'green_beans',      nameRu: 'Стручковая фасоль',    category: 'legume' },
  { name: 'split_peas',       nameRu: 'Горох колотый',        category: 'legume' },

  // --- ЯЙЦА ---
  { name: 'chicken_egg',      nameRu: 'Куриное яйцо',         category: 'egg' },
  { name: 'quail_egg',        nameRu: 'Перепелиное яйцо',     category: 'egg' },

  // --- ХЛЕБ И ВЫПЕЧКА ---
  { name: 'white_bread',      nameRu: 'Белый хлеб',           category: 'bread' },
  { name: 'black_bread',      nameRu: 'Чёрный хлеб',          category: 'bread' },
  { name: 'bread_crumbs',     nameRu: 'Панировочные сухари',  category: 'bread' },
  { name: 'pita',             nameRu: 'Лаваш',                category: 'bread' },
  { name: 'toast_bread',      nameRu: 'Тостовый хлеб',        category: 'bread' },
  { name: 'baguette',         nameRu: 'Багет',                category: 'bread' },
  { name: 'puff_pastry',      nameRu: 'Слоёное тесто',        category: 'bread' },
  { name: 'yeast_dough',      nameRu: 'Дрожжевое тесто',      category: 'bread' },

  // --- МАСЛА ---
  { name: 'sunflower_oil',    nameRu: 'Подсолнечное масло',   category: 'oil' },
  { name: 'olive_oil',        nameRu: 'Оливковое масло',      category: 'oil' },
  { name: 'vegetable_oil',    nameRu: 'Растительное масло',   category: 'oil' },
  { name: 'coconut_oil',      nameRu: 'Кокосовое масло',      category: 'oil' },
  { name: 'sesame_oil',       nameRu: 'Кунжутное масло',      category: 'oil' },

  // --- СОУСЫ ---
  { name: 'soy_sauce',        nameRu: 'Соевый соус',          category: 'sauce' },
  { name: 'tomato_paste',     nameRu: 'Томатная паста',       category: 'sauce' },
  { name: 'ketchup',          nameRu: 'Кетчуп',               category: 'sauce' },
  { name: 'mayonnaise',       nameRu: 'Майонез',              category: 'sauce' },
  { name: 'mustard',          nameRu: 'Горчица',              category: 'sauce' },
  { name: 'vinegar',          nameRu: 'Уксус',                category: 'sauce' },
  { name: 'hot_sauce',        nameRu: 'Острый соус',          category: 'sauce' },
  { name: 'worcestershire',   nameRu: 'Вустерский соус',      category: 'sauce' },
  { name: 'teriyaki',         nameRu: 'Соус терияки',         category: 'sauce' },
  { name: 'pesto',            nameRu: 'Соус песто',           category: 'sauce' },

  // --- СПЕЦИИ ---
  { name: 'salt',             nameRu: 'Соль',                 category: 'spice' },
  { name: 'black_pepper',     nameRu: 'Чёрный перец',         category: 'spice' },
  { name: 'red_pepper',       nameRu: 'Красный перец',        category: 'spice' },
  { name: 'paprika',          nameRu: 'Паприка',              category: 'spice' },
  { name: 'cumin',            nameRu: 'Зира',                 category: 'spice' },
  { name: 'coriander',        nameRu: 'Кориандр',             category: 'spice' },
  { name: 'turmeric',         nameRu: 'Куркума',              category: 'spice' },
  { name: 'cinnamon',         nameRu: 'Корица',               category: 'spice' },
  { name: 'bay_leaf',         nameRu: 'Лавровый лист',        category: 'spice' },
  { name: 'oregano',          nameRu: 'Орегано',              category: 'spice' },
  { name: 'thyme',            nameRu: 'Тимьян',               category: 'spice' },
  { name: 'curry',            nameRu: 'Карри',                category: 'spice' },
  { name: 'nutmeg',           nameRu: 'Мускатный орех',       category: 'spice' },
  { name: 'cloves',           nameRu: 'Гвоздика',             category: 'spice' },
  { name: 'ginger_dry',       nameRu: 'Имбирь сухой',         category: 'spice' },
  { name: 'vanilla',          nameRu: 'Ванилин',              category: 'spice' },
  { name: 'hops_suneli',      nameRu: 'Хмели-сунели',         category: 'spice' },

  // --- СВЕЖАЯ ЗЕЛЕНЬ ---
  { name: 'dill',             nameRu: 'Укроп',                category: 'herb' },
  { name: 'parsley',          nameRu: 'Петрушка',             category: 'herb' },
  { name: 'basil',            nameRu: 'Базилик',              category: 'herb' },
  { name: 'cilantro',         nameRu: 'Кинза',                category: 'herb' },
  { name: 'mint',             nameRu: 'Мята',                 category: 'herb' },
  { name: 'rosemary',         nameRu: 'Розмарин',             category: 'herb' },
  { name: 'tarragon',         nameRu: 'Эстрагон',             category: 'herb' },
  { name: 'ginger_fresh',     nameRu: 'Имбирь свежий',        category: 'herb' },

  // --- ОРЕХИ И СЕМЕНА ---
  { name: 'walnut',           nameRu: 'Грецкий орех',         category: 'nut' },
  { name: 'almond',           nameRu: 'Миндаль',              category: 'nut' },
  { name: 'peanut',           nameRu: 'Арахис',               category: 'nut' },
  { name: 'sunflower_seeds',  nameRu: 'Семечки подсолнуха',   category: 'nut' },
  { name: 'sesame',           nameRu: 'Кунжут',               category: 'nut' },
  { name: 'pine_nuts',        nameRu: 'Кедровые орехи',       category: 'nut' },
  { name: 'cashew',           nameRu: 'Кешью',                category: 'nut' },
  { name: 'pumpkin_seeds',    nameRu: 'Семена тыквы',         category: 'nut' },
  { name: 'flax_seeds',       nameRu: 'Семена льна',          category: 'nut' },
  { name: 'hazelnut',         nameRu: 'Фундук',               category: 'nut' },

  // --- СЛАДКОЕ И ДЛЯ ВЫПЕЧКИ ---
  { name: 'sugar',            nameRu: 'Сахар',                category: 'sweetener' },
  { name: 'powdered_sugar',   nameRu: 'Сахарная пудра',       category: 'sweetener' },
  { name: 'honey',            nameRu: 'Мёд',                  category: 'sweetener' },
  { name: 'baking_powder',    nameRu: 'Разрыхлитель',         category: 'sweetener' },
  { name: 'baking_soda',      nameRu: 'Сода',                 category: 'sweetener' },
  { name: 'cocoa',            nameRu: 'Какао',                category: 'sweetener' },
  { name: 'dark_chocolate',   nameRu: 'Тёмный шоколад',       category: 'sweetener' },
  { name: 'vanilla_sugar',    nameRu: 'Ванильный сахар',      category: 'sweetener' },
  { name: 'jam',              nameRu: 'Варенье',              category: 'sweetener' },
  { name: 'maple_syrup',      nameRu: 'Кленовый сироп',       category: 'sweetener' },

  // --- КОНСЕРВЫ ---
  { name: 'canned_tomatoes',  nameRu: 'Томаты консервированные', category: 'canned' },
  { name: 'canned_corn',      nameRu: 'Кукуруза консервированная', category: 'canned' },
  { name: 'canned_peas',      nameRu: 'Горошек консервированный', category: 'canned' },
  { name: 'canned_beans',     nameRu: 'Фасоль консервированная', category: 'canned' },
  { name: 'canned_tuna',      nameRu: 'Тунец консервированный', category: 'canned' },
  { name: 'olives',           nameRu: 'Маслины/оливки',       category: 'canned' },
  { name: 'canned_mushrooms', nameRu: 'Грибы консервированные', category: 'canned' },
]

module.exports = { ingredients }
