// Ингредиенты для базы MealBot
// protein/fat/carbs — на 100г; avgWeightG — средний вес 1 шт в граммах
// isBasic: true — "всегда есть в доме" (соль, масло и т.д.)

const ingredients = [
  // --- МОЛОЧНЫЕ ---
  { name: 'milk',             nameRu: 'Молоко',               category: 'dairy',     protein: 3.2,  fat: 3.2,  carbs: 4.7  },
  { name: 'butter',           nameRu: 'Сливочное масло',      category: 'dairy',     protein: 0.5,  fat: 82.5, carbs: 0.8,  isBasic: true },
  { name: 'cream',            nameRu: 'Сливки',               category: 'dairy',     protein: 2.5,  fat: 35.0, carbs: 3.3  },
  { name: 'sour_cream',       nameRu: 'Сметана',              category: 'dairy',     protein: 2.8,  fat: 20.0, carbs: 3.2  },
  { name: 'yogurt',           nameRu: 'Йогурт',               category: 'dairy',     protein: 5.0,  fat: 3.2,  carbs: 6.0  },
  { name: 'kefir',            nameRu: 'Кефир',                category: 'dairy',     protein: 3.4,  fat: 3.2,  carbs: 4.3  },
  { name: 'cottage_cheese',   nameRu: 'Творог',               category: 'dairy',     protein: 17.0, fat: 5.0,  carbs: 3.0  },
  { name: 'cheese',           nameRu: 'Сыр твёрдый',          category: 'dairy',     protein: 25.0, fat: 29.0, carbs: 0.4  },
  { name: 'mozzarella',       nameRu: 'Моцарелла',            category: 'dairy',     protein: 22.0, fat: 17.0, carbs: 0.6  },
  { name: 'feta',             nameRu: 'Фета',                 category: 'dairy',     protein: 14.0, fat: 21.0, carbs: 4.0  },
  { name: 'parmesan',         nameRu: 'Пармезан',             category: 'dairy',     protein: 35.0, fat: 28.0, carbs: 3.2  },
  { name: 'cream_cheese',     nameRu: 'Сливочный сыр',        category: 'dairy',     protein: 7.0,  fat: 33.0, carbs: 4.0  },
  { name: 'condensed_milk',   nameRu: 'Сгущённое молоко',     category: 'dairy',     protein: 7.2,  fat: 8.5,  carbs: 55.5 },
  { name: 'ryazhenka',        nameRu: 'Ряженка',              category: 'dairy',     protein: 2.8,  fat: 4.0,  carbs: 4.2  },
  { name: 'processed_cheese', nameRu: 'Плавленый сыр',        category: 'dairy',     protein: 16.0, fat: 19.0, carbs: 3.5  },

  // --- МЯСО ---
  { name: 'chicken_breast',   nameRu: 'Куриная грудка',       category: 'meat',      protein: 23.0, fat: 1.8,  carbs: 0.0  },
  { name: 'chicken_thigh',    nameRu: 'Куриное бедро',        category: 'meat',      protein: 21.0, fat: 11.0, carbs: 0.0  },
  { name: 'chicken_whole',    nameRu: 'Курица целая',          category: 'meat',      protein: 18.0, fat: 15.0, carbs: 0.0  },
  { name: 'chicken_wings',    nameRu: 'Куриные крылья',       category: 'meat',      protein: 19.0, fat: 15.0, carbs: 0.0  },
  { name: 'ground_beef',      nameRu: 'Говяжий фарш',         category: 'meat',      protein: 20.0, fat: 15.0, carbs: 0.0  },
  { name: 'ground_pork',      nameRu: 'Свиной фарш',          category: 'meat',      protein: 17.0, fat: 24.0, carbs: 0.0  },
  { name: 'minced_meat',      nameRu: 'Смешанный фарш',       category: 'meat',      protein: 18.0, fat: 18.0, carbs: 0.0  },
  { name: 'beef',             nameRu: 'Говядина',             category: 'meat',      protein: 26.0, fat: 7.0,  carbs: 0.0  },
  { name: 'pork',             nameRu: 'Свинина',              category: 'meat',      protein: 22.0, fat: 22.0, carbs: 0.0  },
  { name: 'turkey',           nameRu: 'Индейка',              category: 'meat',      protein: 25.0, fat: 4.0,  carbs: 0.0  },
  { name: 'lamb',             nameRu: 'Баранина',             category: 'meat',      protein: 25.0, fat: 16.0, carbs: 0.0  },
  { name: 'bacon',            nameRu: 'Бекон',                category: 'meat',      protein: 23.0, fat: 45.0, carbs: 0.6  },
  { name: 'sausage',          nameRu: 'Колбаса',              category: 'meat',      protein: 14.0, fat: 32.0, carbs: 2.0  },
  { name: 'ham',              nameRu: 'Ветчина',              category: 'meat',      protein: 22.0, fat: 14.0, carbs: 0.0  },
  { name: 'pork_ribs',        nameRu: 'Свиные рёбра',         category: 'meat',      protein: 20.0, fat: 25.0, carbs: 0.0  },

  // --- РЫБА И МОРЕПРОДУКТЫ ---
  { name: 'salmon',           nameRu: 'Лосось',               category: 'fish',      protein: 20.0, fat: 13.0, carbs: 0.0  },
  { name: 'tuna_fresh',       nameRu: 'Тунец свежий',         category: 'fish',      protein: 23.0, fat: 4.5,  carbs: 0.0  },
  { name: 'cod',              nameRu: 'Треска',               category: 'fish',      protein: 17.5, fat: 0.6,  carbs: 0.0  },
  { name: 'herring',          nameRu: 'Сельдь',               category: 'fish',      protein: 18.0, fat: 9.0,  carbs: 0.0  },
  { name: 'mackerel',         nameRu: 'Скумбрия',             category: 'fish',      protein: 18.0, fat: 16.0, carbs: 0.0  },
  { name: 'pollock',          nameRu: 'Минтай',               category: 'fish',      protein: 15.9, fat: 0.9,  carbs: 0.0  },
  { name: 'pike_perch',       nameRu: 'Судак',                category: 'fish',      protein: 18.0, fat: 1.1,  carbs: 0.0  },
  { name: 'shrimp',           nameRu: 'Креветки',             category: 'fish',      protein: 18.0, fat: 2.2,  carbs: 0.0  },
  { name: 'squid',            nameRu: 'Кальмар',              category: 'fish',      protein: 18.0, fat: 2.2,  carbs: 2.0  },
  { name: 'mussels',          nameRu: 'Мидии',                category: 'fish',      protein: 11.0, fat: 2.7,  carbs: 3.3  },
  { name: 'crab_sticks',      nameRu: 'Крабовые палочки',     category: 'fish',      protein: 8.0,  fat: 1.0,  carbs: 14.0 },
  { name: 'red_caviar',       nameRu: 'Красная икра',         category: 'fish',      protein: 31.0, fat: 14.0, carbs: 0.0  },

  // --- ОВОЩИ ---
  { name: 'potato',           nameRu: 'Картофель',            category: 'vegetable', protein: 2.0,  fat: 0.1,  carbs: 17.0, avgWeightG: 150 },
  { name: 'onion',            nameRu: 'Лук репчатый',         category: 'vegetable', protein: 1.4,  fat: 0.0,  carbs: 8.2,  avgWeightG: 150 },
  { name: 'garlic',           nameRu: 'Чеснок',               category: 'vegetable', protein: 6.4,  fat: 0.5,  carbs: 30.0, avgWeightG: 5   },
  { name: 'carrot',           nameRu: 'Морковь',              category: 'vegetable', protein: 1.3,  fat: 0.1,  carbs: 7.0,  avgWeightG: 100 },
  { name: 'tomato',           nameRu: 'Помидор',              category: 'vegetable', protein: 0.6,  fat: 0.2,  carbs: 4.2,  avgWeightG: 100 },
  { name: 'cherry_tomato',    nameRu: 'Помидоры черри',       category: 'vegetable', protein: 0.6,  fat: 0.2,  carbs: 3.8,  avgWeightG: 15  },
  { name: 'cucumber',         nameRu: 'Огурец',               category: 'vegetable', protein: 0.8,  fat: 0.1,  carbs: 2.8,  avgWeightG: 150 },
  { name: 'bell_pepper',      nameRu: 'Болгарский перец',     category: 'vegetable', protein: 1.3,  fat: 0.3,  carbs: 6.7,  avgWeightG: 150 },
  { name: 'cabbage',          nameRu: 'Белокочанная капуста', category: 'vegetable', protein: 1.8,  fat: 0.1,  carbs: 4.7  },
  { name: 'broccoli',         nameRu: 'Брокколи',             category: 'vegetable', protein: 2.8,  fat: 0.4,  carbs: 5.2  },
  { name: 'cauliflower',      nameRu: 'Цветная капуста',      category: 'vegetable', protein: 2.5,  fat: 0.3,  carbs: 4.2  },
  { name: 'zucchini',         nameRu: 'Кабачок',              category: 'vegetable', protein: 0.6,  fat: 0.3,  carbs: 4.6,  avgWeightG: 250 },
  { name: 'eggplant',         nameRu: 'Баклажан',             category: 'vegetable', protein: 1.2,  fat: 0.1,  carbs: 4.5,  avgWeightG: 300 },
  { name: 'beet',             nameRu: 'Свёкла',               category: 'vegetable', protein: 1.5,  fat: 0.1,  carbs: 8.8,  avgWeightG: 200 },
  { name: 'celery',           nameRu: 'Сельдерей',            category: 'vegetable', protein: 0.9,  fat: 0.1,  carbs: 2.1  },
  { name: 'spinach',          nameRu: 'Шпинат',               category: 'vegetable', protein: 2.9,  fat: 0.4,  carbs: 2.0  },
  { name: 'lettuce',          nameRu: 'Листовой салат',       category: 'vegetable', protein: 1.3,  fat: 0.3,  carbs: 2.0  },
  { name: 'corn',             nameRu: 'Кукуруза',             category: 'vegetable', protein: 3.3,  fat: 1.2,  carbs: 22.5 },
  { name: 'peas',             nameRu: 'Зелёный горошек',      category: 'vegetable', protein: 5.0,  fat: 0.2,  carbs: 13.8 },
  { name: 'asparagus',        nameRu: 'Спаржа',               category: 'vegetable', protein: 2.2,  fat: 0.1,  carbs: 3.1  },
  { name: 'leek',             nameRu: 'Лук-порей',            category: 'vegetable', protein: 2.0,  fat: 0.3,  carbs: 6.5  },
  { name: 'radish',           nameRu: 'Редис',                category: 'vegetable', protein: 1.2,  fat: 0.1,  carbs: 3.4,  avgWeightG: 15  },
  { name: 'pumpkin',          nameRu: 'Тыква',                category: 'vegetable', protein: 1.0,  fat: 0.1,  carbs: 4.4  },
  { name: 'green_onion',      nameRu: 'Зелёный лук',          category: 'vegetable', protein: 1.3,  fat: 0.1,  carbs: 4.6  },
  { name: 'mushrooms',        nameRu: 'Шампиньоны',           category: 'vegetable', protein: 4.3,  fat: 1.0,  carbs: 1.0  },
  { name: 'wild_mushrooms',   nameRu: 'Лесные грибы',         category: 'vegetable', protein: 3.7,  fat: 1.7,  carbs: 1.1  },
  { name: 'sweet_potato',     nameRu: 'Батат',                category: 'vegetable', protein: 2.0,  fat: 0.1,  carbs: 20.0, avgWeightG: 200 },
  { name: 'artichoke',        nameRu: 'Артишок',              category: 'vegetable', protein: 3.3,  fat: 0.2,  carbs: 5.1  },
  { name: 'arugula',          nameRu: 'Руккола',              category: 'vegetable', protein: 2.6,  fat: 0.7,  carbs: 2.1  },
  { name: 'chinese_cabbage',  nameRu: 'Пекинская капуста',    category: 'vegetable', protein: 1.2,  fat: 0.2,  carbs: 2.0  },

  // --- ФРУКТЫ И ЯГОДЫ ---
  { name: 'apple',            nameRu: 'Яблоко',               category: 'fruit',     protein: 0.4,  fat: 0.4,  carbs: 11.0, avgWeightG: 180 },
  { name: 'banana',           nameRu: 'Банан',                category: 'fruit',     protein: 1.5,  fat: 0.5,  carbs: 21.0, avgWeightG: 120 },
  { name: 'orange',           nameRu: 'Апельсин',             category: 'fruit',     protein: 0.9,  fat: 0.2,  carbs: 8.1,  avgWeightG: 180 },
  { name: 'lemon',            nameRu: 'Лимон',                category: 'fruit',     protein: 0.9,  fat: 0.1,  carbs: 3.0,  avgWeightG: 100 },
  { name: 'lime',             nameRu: 'Лайм',                 category: 'fruit',     protein: 0.7,  fat: 0.2,  carbs: 7.1,  avgWeightG: 67  },
  { name: 'strawberry',       nameRu: 'Клубника',             category: 'fruit',     protein: 0.8,  fat: 0.4,  carbs: 7.5,  avgWeightG: 10  },
  { name: 'blueberry',        nameRu: 'Черника',              category: 'fruit',     protein: 1.1,  fat: 0.4,  carbs: 7.6  },
  { name: 'grape',            nameRu: 'Виноград',             category: 'fruit',     protein: 0.6,  fat: 0.2,  carbs: 15.4, avgWeightG: 5   },
  { name: 'pear',             nameRu: 'Груша',                category: 'fruit',     protein: 0.4,  fat: 0.3,  carbs: 10.7, avgWeightG: 180 },
  { name: 'peach',            nameRu: 'Персик',               category: 'fruit',     protein: 0.9,  fat: 0.1,  carbs: 9.5,  avgWeightG: 150 },
  { name: 'mango',            nameRu: 'Манго',                category: 'fruit',     protein: 0.5,  fat: 0.3,  carbs: 11.5, avgWeightG: 300 },
  { name: 'pineapple',        nameRu: 'Ананас',               category: 'fruit',     protein: 0.5,  fat: 0.1,  carbs: 11.9, avgWeightG: 900 },
  { name: 'raspberry',        nameRu: 'Малина',               category: 'fruit',     protein: 0.8,  fat: 0.5,  carbs: 8.3  },
  { name: 'cherry',           nameRu: 'Вишня',                category: 'fruit',     protein: 1.1,  fat: 0.4,  carbs: 10.6, avgWeightG: 7   },
  { name: 'avocado',          nameRu: 'Авокадо',              category: 'fruit',     protein: 2.0,  fat: 15.0, carbs: 1.8,  avgWeightG: 200 },
  { name: 'watermelon',       nameRu: 'Арбуз',                category: 'fruit',     protein: 0.6,  fat: 0.1,  carbs: 5.8  },
  { name: 'pomegranate',      nameRu: 'Гранат',               category: 'fruit',     protein: 1.0,  fat: 0.5,  carbs: 14.5, avgWeightG: 300 },
  { name: 'kiwi',             nameRu: 'Киви',                 category: 'fruit',     protein: 1.1,  fat: 0.6,  carbs: 10.3, avgWeightG: 75  },

  // --- КРУПЫ И ЗЛАКИ ---
  { name: 'rice',             nameRu: 'Рис',                  category: 'grain',     protein: 7.0,  fat: 1.8,  carbs: 74.0 },
  { name: 'buckwheat',        nameRu: 'Гречка',               category: 'grain',     protein: 12.6, fat: 3.3,  carbs: 57.1 },
  { name: 'oatmeal',          nameRu: 'Овсяные хлопья',       category: 'grain',     protein: 12.0, fat: 6.0,  carbs: 60.0 },
  { name: 'pasta',            nameRu: 'Макароны',             category: 'grain',     protein: 11.0, fat: 1.3,  carbs: 70.5 },
  { name: 'spaghetti',        nameRu: 'Спагетти',             category: 'grain',     protein: 11.0, fat: 1.3,  carbs: 70.5 },
  { name: 'wheat_flour',      nameRu: 'Пшеничная мука',       category: 'grain',     protein: 10.3, fat: 1.1,  carbs: 70.6 },
  { name: 'whole_wheat_flour',nameRu: 'Цельнозерновая мука',  category: 'grain',     protein: 13.0, fat: 2.0,  carbs: 59.0 },
  { name: 'semolina',         nameRu: 'Манная крупа',         category: 'grain',     protein: 10.3, fat: 1.0,  carbs: 70.0 },
  { name: 'barley',           nameRu: 'Перловка',             category: 'grain',     protein: 9.3,  fat: 1.1,  carbs: 66.9 },
  { name: 'millet',           nameRu: 'Пшено',                category: 'grain',     protein: 11.5, fat: 3.3,  carbs: 66.5 },
  { name: 'couscous',         nameRu: 'Кускус',               category: 'grain',     protein: 12.8, fat: 0.6,  carbs: 72.4 },
  { name: 'bulgur',           nameRu: 'Булгур',               category: 'grain',     protein: 12.3, fat: 1.3,  carbs: 65.2 },
  { name: 'cornmeal',         nameRu: 'Кукурузная крупа',     category: 'grain',     protein: 8.3,  fat: 1.2,  carbs: 71.0 },
  { name: 'starch',           nameRu: 'Крахмал',              category: 'grain',     protein: 0.3,  fat: 0.0,  carbs: 85.0 },

  // --- БОБОВЫЕ ---
  { name: 'lentils',          nameRu: 'Чечевица',             category: 'legume',    protein: 24.0, fat: 1.5,  carbs: 42.0 },
  { name: 'chickpeas',        nameRu: 'Нут',                  category: 'legume',    protein: 20.0, fat: 4.3,  carbs: 46.0 },
  { name: 'red_beans',        nameRu: 'Красная фасоль',       category: 'legume',    protein: 22.0, fat: 1.5,  carbs: 47.0 },
  { name: 'white_beans',      nameRu: 'Белая фасоль',         category: 'legume',    protein: 21.0, fat: 1.0,  carbs: 46.0 },
  { name: 'green_beans',      nameRu: 'Стручковая фасоль',    category: 'legume',    protein: 2.0,  fat: 0.2,  carbs: 3.6  },
  { name: 'split_peas',       nameRu: 'Горох колотый',        category: 'legume',    protein: 23.0, fat: 1.2,  carbs: 50.3 },

  // --- ЯЙЦА ---
  { name: 'chicken_egg',      nameRu: 'Куриное яйцо',         category: 'egg',       protein: 12.7, fat: 11.5, carbs: 0.7,  avgWeightG: 60  },
  { name: 'quail_egg',        nameRu: 'Перепелиное яйцо',     category: 'egg',       protein: 13.0, fat: 11.0, carbs: 0.6,  avgWeightG: 12  },

  // --- ХЛЕБ И ВЫПЕЧКА ---
  { name: 'white_bread',      nameRu: 'Белый хлеб',           category: 'bread',     protein: 7.7,  fat: 2.4,  carbs: 48.3 },
  { name: 'black_bread',      nameRu: 'Чёрный хлеб',          category: 'bread',     protein: 6.8,  fat: 1.3,  carbs: 40.7 },
  { name: 'bread_crumbs',     nameRu: 'Панировочные сухари',  category: 'bread',     protein: 11.0, fat: 2.4,  carbs: 73.0 },
  { name: 'pita',             nameRu: 'Лаваш',                category: 'bread',     protein: 8.5,  fat: 1.1,  carbs: 55.0 },
  { name: 'toast_bread',      nameRu: 'Тостовый хлеб',        category: 'bread',     protein: 7.6,  fat: 3.0,  carbs: 46.0 },
  { name: 'baguette',         nameRu: 'Багет',                category: 'bread',     protein: 8.0,  fat: 1.5,  carbs: 55.0 },
  { name: 'puff_pastry',      nameRu: 'Слоёное тесто',        category: 'bread',     protein: 7.4,  fat: 24.0, carbs: 31.0 },
  { name: 'yeast_dough',      nameRu: 'Дрожжевое тесто',      category: 'bread',     protein: 7.8,  fat: 4.0,  carbs: 45.0 },

  // --- МАСЛА ---
  { name: 'sunflower_oil',    nameRu: 'Подсолнечное масло',   category: 'oil',       protein: 0.0,  fat: 99.9, carbs: 0.0,  isBasic: true },
  { name: 'olive_oil',        nameRu: 'Оливковое масло',      category: 'oil',       protein: 0.0,  fat: 99.8, carbs: 0.0,  isBasic: true },
  { name: 'vegetable_oil',    nameRu: 'Растительное масло',   category: 'oil',       protein: 0.0,  fat: 99.9, carbs: 0.0,  isBasic: true },
  { name: 'coconut_oil',      nameRu: 'Кокосовое масло',      category: 'oil',       protein: 0.0,  fat: 99.1, carbs: 0.0  },
  { name: 'sesame_oil',       nameRu: 'Кунжутное масло',      category: 'oil',       protein: 0.0,  fat: 99.9, carbs: 0.0  },

  // --- СОУСЫ ---
  { name: 'soy_sauce',        nameRu: 'Соевый соус',          category: 'sauce',     protein: 6.0,  fat: 0.0,  carbs: 6.6,  isBasic: true },
  { name: 'tomato_paste',     nameRu: 'Томатная паста',       category: 'sauce',     protein: 4.5,  fat: 0.5,  carbs: 20.5 },
  { name: 'ketchup',          nameRu: 'Кетчуп',               category: 'sauce',     protein: 1.8,  fat: 0.1,  carbs: 22.3 },
  { name: 'mayonnaise',       nameRu: 'Майонез',              category: 'sauce',     protein: 2.4,  fat: 67.0, carbs: 2.6  },
  { name: 'mustard',          nameRu: 'Горчица',              category: 'sauce',     protein: 6.3,  fat: 6.4,  carbs: 8.6  },
  { name: 'vinegar',          nameRu: 'Уксус',                category: 'sauce',     protein: 0.0,  fat: 0.0,  carbs: 0.6,  isBasic: true },
  { name: 'hot_sauce',        nameRu: 'Острый соус',          category: 'sauce',     protein: 0.5,  fat: 0.3,  carbs: 2.0  },
  { name: 'worcestershire',   nameRu: 'Вустерский соус',      category: 'sauce',     protein: 0.8,  fat: 0.0,  carbs: 20.0 },
  { name: 'teriyaki',         nameRu: 'Соус терияки',         category: 'sauce',     protein: 3.5,  fat: 0.5,  carbs: 18.0 },
  { name: 'pesto',            nameRu: 'Соус песто',           category: 'sauce',     protein: 5.4,  fat: 22.0, carbs: 6.0  },

  // --- СПЕЦИИ ---
  { name: 'salt',             nameRu: 'Соль',                 category: 'spice',     protein: 0.0,  fat: 0.0,  carbs: 0.0,  isBasic: true },
  { name: 'black_pepper',     nameRu: 'Чёрный перец',         category: 'spice',     protein: 10.4, fat: 3.3,  carbs: 38.7, isBasic: true },
  { name: 'red_pepper',       nameRu: 'Красный перец',        category: 'spice',     protein: 12.0, fat: 17.3, carbs: 34.8, isBasic: true },
  { name: 'paprika',          nameRu: 'Паприка',              category: 'spice',     protein: 14.8, fat: 12.9, carbs: 53.9, isBasic: true },
  { name: 'cumin',            nameRu: 'Зира',                 category: 'spice',     protein: 17.8, fat: 22.3, carbs: 33.7 },
  { name: 'coriander',        nameRu: 'Кориандр',             category: 'spice',     protein: 12.4, fat: 17.8, carbs: 54.9 },
  { name: 'turmeric',         nameRu: 'Куркума',              category: 'spice',     protein: 9.7,  fat: 3.3,  carbs: 65.0 },
  { name: 'cinnamon',         nameRu: 'Корица',               category: 'spice',     protein: 4.0,  fat: 1.2,  carbs: 79.8, isBasic: true },
  { name: 'bay_leaf',         nameRu: 'Лавровый лист',        category: 'spice',     protein: 7.6,  fat: 8.4,  carbs: 48.7, isBasic: true },
  { name: 'oregano',          nameRu: 'Орегано',              category: 'spice',     protein: 9.0,  fat: 4.3,  carbs: 68.9, isBasic: true },
  { name: 'thyme',            nameRu: 'Тимьян',               category: 'spice',     protein: 9.1,  fat: 7.4,  carbs: 63.9, isBasic: true },
  { name: 'curry',            nameRu: 'Карри',                category: 'spice',     protein: 14.3, fat: 12.8, carbs: 55.8 },
  { name: 'nutmeg',           nameRu: 'Мускатный орех',       category: 'spice',     protein: 5.8,  fat: 36.3, carbs: 49.3 },
  { name: 'cloves',           nameRu: 'Гвоздика',             category: 'spice',     protein: 6.0,  fat: 13.0, carbs: 65.5 },
  { name: 'ginger_dry',       nameRu: 'Имбирь сухой',         category: 'spice',     protein: 8.7,  fat: 4.2,  carbs: 71.0 },
  { name: 'vanilla',          nameRu: 'Ванилин',              category: 'spice',     protein: 0.1,  fat: 0.1,  carbs: 12.6, isBasic: true },
  { name: 'hops_suneli',      nameRu: 'Хмели-сунели',         category: 'spice',     protein: 10.0, fat: 6.0,  carbs: 50.0, isBasic: true },

  // --- СВЕЖАЯ ЗЕЛЕНЬ ---
  { name: 'dill',             nameRu: 'Укроп',                category: 'herb',      protein: 2.5,  fat: 0.5,  carbs: 4.1  },
  { name: 'parsley',          nameRu: 'Петрушка',             category: 'herb',      protein: 3.7,  fat: 0.4,  carbs: 6.3  },
  { name: 'basil',            nameRu: 'Базилик',              category: 'herb',      protein: 3.2,  fat: 0.6,  carbs: 4.3  },
  { name: 'cilantro',         nameRu: 'Кинза',                category: 'herb',      protein: 2.1,  fat: 0.5,  carbs: 3.7  },
  { name: 'mint',             nameRu: 'Мята',                 category: 'herb',      protein: 3.3,  fat: 0.7,  carbs: 8.0  },
  { name: 'rosemary',         nameRu: 'Розмарин',             category: 'herb',      protein: 3.3,  fat: 5.9,  carbs: 20.7 },
  { name: 'tarragon',         nameRu: 'Эстрагон',             category: 'herb',      protein: 3.7,  fat: 0.4,  carbs: 5.3  },
  { name: 'ginger_fresh',     nameRu: 'Имбирь свежий',        category: 'herb',      protein: 1.8,  fat: 0.8,  carbs: 15.8 },

  // --- ОРЕХИ И СЕМЕНА ---
  { name: 'walnut',           nameRu: 'Грецкий орех',         category: 'nut',       protein: 15.2, fat: 65.2, carbs: 7.0  },
  { name: 'almond',           nameRu: 'Миндаль',              category: 'nut',       protein: 21.2, fat: 49.9, carbs: 6.9  },
  { name: 'peanut',           nameRu: 'Арахис',               category: 'nut',       protein: 26.3, fat: 45.2, carbs: 9.9  },
  { name: 'sunflower_seeds',  nameRu: 'Семечки подсолнуха',   category: 'nut',       protein: 20.7, fat: 52.9, carbs: 10.5 },
  { name: 'sesame',           nameRu: 'Кунжут',               category: 'nut',       protein: 17.7, fat: 48.7, carbs: 12.2 },
  { name: 'pine_nuts',        nameRu: 'Кедровые орехи',       category: 'nut',       protein: 11.6, fat: 61.0, carbs: 19.3 },
  { name: 'cashew',           nameRu: 'Кешью',                category: 'nut',       protein: 18.2, fat: 43.9, carbs: 22.3 },
  { name: 'pumpkin_seeds',    nameRu: 'Семена тыквы',         category: 'nut',       protein: 24.5, fat: 45.8, carbs: 13.5 },
  { name: 'flax_seeds',       nameRu: 'Семена льна',          category: 'nut',       protein: 18.3, fat: 42.2, carbs: 1.6  },
  { name: 'hazelnut',         nameRu: 'Фундук',               category: 'nut',       protein: 13.0, fat: 61.0, carbs: 9.4  },

  // --- СЛАДКОЕ И ДЛЯ ВЫПЕЧКИ ---
  { name: 'sugar',            nameRu: 'Сахар',                category: 'sweetener', protein: 0.0,  fat: 0.0,  carbs: 99.8, isBasic: true },
  { name: 'powdered_sugar',   nameRu: 'Сахарная пудра',       category: 'sweetener', protein: 0.0,  fat: 0.0,  carbs: 99.9 },
  { name: 'honey',            nameRu: 'Мёд',                  category: 'sweetener', protein: 0.8,  fat: 0.0,  carbs: 80.3 },
  { name: 'baking_powder',    nameRu: 'Разрыхлитель',         category: 'sweetener', protein: 0.0,  fat: 0.0,  carbs: 27.7, isBasic: true },
  { name: 'baking_soda',      nameRu: 'Сода',                 category: 'sweetener', protein: 0.0,  fat: 0.0,  carbs: 0.0,  isBasic: true },
  { name: 'cocoa',            nameRu: 'Какао',                category: 'sweetener', protein: 24.3, fat: 15.0, carbs: 10.2 },
  { name: 'dark_chocolate',   nameRu: 'Тёмный шоколад',       category: 'sweetener', protein: 6.2,  fat: 35.4, carbs: 48.2 },
  { name: 'vanilla_sugar',    nameRu: 'Ванильный сахар',      category: 'sweetener', protein: 0.0,  fat: 0.0,  carbs: 95.0, isBasic: true },
  { name: 'jam',              nameRu: 'Варенье',              category: 'sweetener', protein: 0.3,  fat: 0.0,  carbs: 65.0 },
  { name: 'maple_syrup',      nameRu: 'Кленовый сироп',       category: 'sweetener', protein: 0.0,  fat: 0.3,  carbs: 67.0 },

  // --- КОНСЕРВЫ ---
  { name: 'canned_tomatoes',  nameRu: 'Томаты консервированные', category: 'canned', protein: 0.9,  fat: 0.2,  carbs: 5.0  },
  { name: 'canned_corn',      nameRu: 'Кукуруза консервированная', category: 'canned', protein: 2.2, fat: 0.6,  carbs: 16.3 },
  { name: 'canned_peas',      nameRu: 'Горошек консервированный', category: 'canned', protein: 3.6, fat: 0.1,  carbs: 8.7  },
  { name: 'canned_beans',     nameRu: 'Фасоль консервированная', category: 'canned', protein: 7.0,  fat: 0.5,  carbs: 14.0 },
  { name: 'canned_tuna',      nameRu: 'Тунец консервированный', category: 'canned',  protein: 22.0, fat: 5.0,  carbs: 0.0  },
  { name: 'olives',           nameRu: 'Маслины/оливки',       category: 'canned',    protein: 0.8,  fat: 10.7, carbs: 0.8,  avgWeightG: 5  },
  { name: 'canned_mushrooms', nameRu: 'Грибы консервированные', category: 'canned',  protein: 2.5,  fat: 0.5,  carbs: 3.0  },
]

module.exports = { ingredients }
