const { PrismaClient } = require('@prisma/client')
const { ingredients } = require('./ingredients')
const prisma = new PrismaClient()

const dishes = [
  {
    name: 'omelette',
    nameRu: 'Омлет',
    description: 'Классический завтрак — воздушный омлет на сливочном масле',
    categories: ['BREAKFAST'],
    cuisine: 'Русская',
    mealTime: ['breakfast'],
    tags: ['быстро', 'вегетарианское', 'без глютена', 'горячее'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 220,
    recipe: `## Омлет классический\n\n**Ингредиенты:**\n- 3 яйца\n- 50 мл молока\n- Соль, перец\n- Сливочное масло\n\n**Приготовление:**\n1. Взбить яйца с молоком, посолить\n2. Растопить масло на сковороде\n3. Вылить смесь, готовить 3-4 минуты\n4. Сложить пополам, подавать горячим`,
    ingredients: [
      { name: 'chicken_egg', amount: '3 шт' },
      { name: 'milk', amount: '50 мл' },
      { name: 'butter', amount: '1 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'black_pepper', amount: 'по вкусу' },
    ],
  },
  {
    name: 'omelette_with_tomatoes',
    nameRu: 'Омлет с помидорами',
    description: 'Омлет с сочными помидорами и свежей зеленью',
    categories: ['BREAKFAST'],
    cuisine: 'Русская',
    mealTime: ['breakfast'],
    tags: ['быстро', 'вегетарианское', 'без глютена'],
    cookTime: 12,
    difficulty: 'easy',
    calories: 250,
    recipe: `## Омлет с помидорами\n\n**Приготовление:**\n1. Нарезать помидор кубиками\n2. Взбить яйца с молоком\n3. Обжарить помидоры 1-2 минуты\n4. Залить яичной смесью, готовить до готовности`,
    ingredients: [
      { name: 'chicken_egg', amount: '3 шт' },
      { name: 'milk', amount: '50 мл' },
      { name: 'butter', amount: '1 ст.л.' },
      { name: 'tomato', amount: '1 шт' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'dill', amount: 'пучок' },
    ],
  },
  {
    name: 'scrambled_eggs',
    nameRu: 'Яичница глазунья',
    description: 'Простая яичница — классика завтрака',
    categories: ['BREAKFAST'],
    cuisine: 'Русская',
    mealTime: ['breakfast'],
    tags: ['быстро', 'вегетарианское', 'без глютена'],
    cookTime: 7,
    difficulty: 'easy',
    calories: 180,
    recipe: `## Яичница глазунья\n\n1. Разогреть сковороду с маслом\n2. Разбить яйца, посолить\n3. Жарить 3-4 минуты`,
    ingredients: [
      { name: 'chicken_egg', amount: '2-3 шт' },
      { name: 'butter', amount: '1 ч.л.' },
      { name: 'salt', amount: 'по вкусу' },
    ],
  },
  {
    name: 'oatmeal_dish',
    nameRu: 'Овсяная каша',
    description: 'Питательная овсянка с мёдом и бананом',
    categories: ['BREAKFAST'],
    cuisine: 'Европейская',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'здоровое', 'быстро'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 300,
    recipe: `## Овсяная каша\n\n1. Залить овсянку молоком 1:2\n2. Варить 5-7 минут помешивая\n3. Добавить мёд и банан`,
    ingredients: [
      { name: 'oatmeal', amount: '100 г' },
      { name: 'milk', amount: '200 мл' },
      { name: 'honey', amount: '1 ст.л.' },
      { name: 'banana', amount: '1 шт' },
    ],
  },
  {
    name: 'pancakes',
    nameRu: 'Блины',
    description: 'Тонкие русские блины — к чаю или со сметаной',
    categories: ['BREAKFAST', 'DESSERT'],
    cuisine: 'Русская',
    mealTime: ['breakfast', 'snack'],
    tags: ['вегетарианское', 'традиционное'],
    cookTime: 30,
    difficulty: 'medium',
    calories: 350,
    recipe: `## Блины\n\n**Ингредиенты:**\n- 2 яйца\n- 500 мл молока\n- 1 стакан муки\n- 1 ст.л. сахара\n- Щепотка соли\n- 2 ст.л. масла\n\n**Приготовление:**\n1. Смешать яйца, молоко, муку, сахар, соль\n2. Добавить масло в тесто\n3. Жарить на горячей сковороде по 1-2 минуты с каждой стороны`,
    ingredients: [
      { name: 'chicken_egg', amount: '2 шт' },
      { name: 'milk', amount: '500 мл' },
      { name: 'wheat_flour', amount: '1 стакан' },
      { name: 'sugar', amount: '1 ст.л.' },
      { name: 'salt', amount: 'щепотка' },
      { name: 'butter', amount: '2 ст.л.' },
    ],
  },
  {
    name: 'cottage_cheese_pancakes',
    nameRu: 'Сырники',
    description: 'Творожные сырники — пышные и нежные',
    categories: ['BREAKFAST'],
    cuisine: 'Русская',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'сытное'],
    cookTime: 25,
    difficulty: 'easy',
    calories: 320,
    recipe: `## Сырники\n\n1. Смешать творог, яйца, муку, сахар, соль\n2. Сформировать лепёшки\n3. Обжарить на масле по 3 минуты с каждой стороны\n4. Подавать со сметаной`,
    ingredients: [
      { name: 'cottage_cheese', amount: '500 г' },
      { name: 'chicken_egg', amount: '2 шт' },
      { name: 'wheat_flour', amount: '3 ст.л.' },
      { name: 'sugar', amount: '2 ст.л.' },
      { name: 'salt', amount: 'щепотка' },
      { name: 'butter', amount: '2 ст.л.' },
      { name: 'sour_cream', amount: 'для подачи' },
    ],
  },
  {
    name: 'chicken_soup',
    nameRu: 'Куриный суп',
    description: 'Наваристый куриный суп с овощами',
    categories: ['SOUP', 'LUNCH'],
    cuisine: 'Русская',
    mealTime: ['lunch', 'dinner'],
    tags: ['сытное', 'традиционное', 'суп'],
    cookTime: 60,
    difficulty: 'medium',
    calories: 180,
    recipe: `## Куриный суп\n\n1. Отварить курицу 40 минут, снять пену\n2. Добавить нарезанные морковь, лук, картофель\n3. Варить ещё 20 минут\n4. Посолить, добавить зелень`,
    ingredients: [
      { name: 'chicken_breast', amount: '400 г' },
      { name: 'potato', amount: '3 шт' },
      { name: 'carrot', amount: '1 шт' },
      { name: 'onion', amount: '1 шт' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'dill', amount: 'пучок' },
      { name: 'parsley', amount: 'пучок' },
    ],
  },
  {
    name: 'pasta_carbonara',
    nameRu: 'Паста карбонара',
    description: 'Классическая итальянская паста в сливочно-яичном соусе',
    categories: ['LUNCH', 'DINNER'],
    cuisine: 'Итальянская',
    mealTime: ['lunch', 'dinner'],
    tags: ['итальянское', 'сытное', 'быстро'],
    cookTime: 20,
    difficulty: 'medium',
    calories: 520,
    recipe: `## Паста карбонара\n\n1. Отварить пасту al dente\n2. Смешать яйца, тёртый сыр, перец\n3. Обжарить бекон\n4. Смешать горячую пасту с яичной смесью\n5. Подавать сразу`,
    ingredients: [
      { name: 'pasta', amount: '200 г' },
      { name: 'chicken_egg', amount: '3 шт' },
      { name: 'parmesan', amount: '50 г' },
      { name: 'bacon', amount: '100 г' },
      { name: 'black_pepper', amount: 'по вкусу' },
      { name: 'salt', amount: 'по вкусу' },
    ],
  },
  {
    name: 'fried_potatoes',
    nameRu: 'Жареная картошка',
    description: 'Хрустящая жареная картошка с луком',
    categories: ['LUNCH', 'DINNER'],
    cuisine: 'Русская',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'сытное', 'быстро', 'традиционное'],
    cookTime: 25,
    difficulty: 'easy',
    calories: 380,
    recipe: `## Жареная картошка\n\n1. Нарезать картофель ломтиками\n2. Разогреть масло на сковороде\n3. Жарить 15-20 минут, перемешивая\n4. Добавить лук, жарить ещё 5 минут\n5. Посолить, добавить укроп`,
    ingredients: [
      { name: 'potato', amount: '500 г' },
      { name: 'onion', amount: '1 шт' },
      { name: 'sunflower_oil', amount: '3 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'dill', amount: 'пучок' },
    ],
  },
  {
    name: 'rice_with_vegetables',
    nameRu: 'Рис с овощами',
    description: 'Лёгкий рис с болгарским перцем и морковью',
    categories: ['LUNCH'],
    cuisine: 'Азиатская',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'здоровое', 'без глютена'],
    cookTime: 30,
    difficulty: 'easy',
    calories: 280,
    recipe: `## Рис с овощами\n\n1. Промыть и отварить рис\n2. Нарезать морковь, перец, лук\n3. Обжарить овощи 7-10 минут\n4. Смешать с рисом, посолить`,
    ingredients: [
      { name: 'rice', amount: '200 г' },
      { name: 'carrot', amount: '1 шт' },
      { name: 'bell_pepper', amount: '1 шт' },
      { name: 'onion', amount: '1 шт' },
      { name: 'sunflower_oil', amount: '2 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
    ],
  },
  {
    name: 'greek_salad',
    nameRu: 'Греческий салат',
    description: 'Свежий средиземноморский салат с сыром фета',
    categories: ['SALAD'],
    cuisine: 'Греческая',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'без глютена', 'свежее', 'быстро'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 220,
    recipe: `## Греческий салат\n\n1. Нарезать помидоры, огурцы, перец\n2. Добавить сыр фета кубиками\n3. Заправить оливковым маслом и лимоном\n4. Посолить, поперчить`,
    ingredients: [
      { name: 'tomato', amount: '2 шт' },
      { name: 'cucumber', amount: '1 шт' },
      { name: 'bell_pepper', amount: '1 шт' },
      { name: 'feta', amount: '100 г' },
      { name: 'olive_oil', amount: '2 ст.л.' },
      { name: 'lemon', amount: '1/2 шт' },
      { name: 'salt', amount: 'по вкусу' },
    ],
  },
  {
    name: 'mushroom_soup',
    nameRu: 'Грибной суп',
    description: 'Ароматный суп с грибами',
    categories: ['SOUP'],
    cuisine: 'Русская',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'суп', 'ароматное'],
    cookTime: 40,
    difficulty: 'easy',
    calories: 150,
    recipe: `## Грибной суп\n\n1. Обжарить грибы с луком\n2. Добавить нарезанный картофель\n3. Залить водой, варить 25 минут\n4. Добавить сметану, зелень`,
    ingredients: [
      { name: 'mushrooms', amount: '300 г' },
      { name: 'potato', amount: '3 шт' },
      { name: 'onion', amount: '1 шт' },
      { name: 'sour_cream', amount: '2 ст.л.' },
      { name: 'butter', amount: '1 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'dill', amount: 'пучок' },
    ],
  },
  {
    name: 'beef_stew',
    nameRu: 'Тушёная говядина с овощами',
    description: 'Нежная говядина в томатном соусе',
    categories: ['DINNER'],
    cuisine: 'Русская',
    mealTime: ['dinner'],
    tags: ['сытное', 'традиционное'],
    cookTime: 90,
    difficulty: 'medium',
    calories: 420,
    recipe: `## Тушёная говядина\n\n1. Обжарить говядину кусочками\n2. Добавить лук, морковь\n3. Добавить томаты, тушить 60-70 минут\n4. Посолить, поперчить`,
    ingredients: [
      { name: 'beef', amount: '500 г' },
      { name: 'onion', amount: '1 шт' },
      { name: 'carrot', amount: '1 шт' },
      { name: 'canned_tomatoes', amount: '400 г' },
      { name: 'garlic', amount: '3 зубчика' },
      { name: 'olive_oil', amount: '2 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'black_pepper', amount: 'по вкусу' },
    ],
  },
  {
    name: 'vegetable_stir_fry',
    nameRu: 'Жаркое из овощей',
    description: 'Быстрое жаркое с соевым соусом по-азиатски',
    categories: ['LUNCH', 'DINNER'],
    cuisine: 'Азиатская',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'азиатское', 'быстро', 'здоровое'],
    cookTime: 15,
    difficulty: 'easy',
    calories: 200,
    recipe: `## Жаркое из овощей\n\n1. Нарезать все овощи соломкой\n2. Обжарить на сильном огне 5-7 минут\n3. Добавить соевый соус, чеснок\n4. Подавать с рисом`,
    ingredients: [
      { name: 'bell_pepper', amount: '2 шт' },
      { name: 'carrot', amount: '1 шт' },
      { name: 'mushrooms', amount: '200 г' },
      { name: 'onion', amount: '1 шт' },
      { name: 'garlic', amount: '2 зубчика' },
      { name: 'soy_sauce', amount: '3 ст.л.' },
      { name: 'sunflower_oil', amount: '2 ст.л.' },
    ],
  },
  {
    name: 'chicken_with_rice',
    nameRu: 'Курица с рисом',
    description: 'Запечённая курица с рассыпчатым рисом',
    categories: ['DINNER', 'LUNCH'],
    cuisine: 'Русская',
    mealTime: ['lunch', 'dinner'],
    tags: ['сытное', 'традиционное', 'без глютена'],
    cookTime: 50,
    difficulty: 'easy',
    calories: 450,
    recipe: `## Курица с рисом\n\n1. Замариновать курицу с чесноком и специями\n2. Обжарить до золотистой корочки\n3. Отварить рис\n4. Подавать вместе`,
    ingredients: [
      { name: 'chicken_breast', amount: '400 г' },
      { name: 'rice', amount: '200 г' },
      { name: 'garlic', amount: '3 зубчика' },
      { name: 'sunflower_oil', amount: '2 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'black_pepper', amount: 'по вкусу' },
    ],
  },
  {
    name: 'semolina_porridge',
    nameRu: 'Манная каша',
    description: 'Нежная манная каша с маслом',
    categories: ['BREAKFAST'],
    cuisine: 'Русская',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'нежное', 'традиционное'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 260,
    recipe: `## Манная каша\n\n1. Вскипятить молоко\n2. Всыпать манку тонкой струйкой, помешивая\n3. Варить 5 минут\n4. Добавить масло, сахар по вкусу`,
    ingredients: [
      { name: 'semolina', amount: '4 ст.л.' },
      { name: 'milk', amount: '400 мл' },
      { name: 'butter', amount: '1 ст.л.' },
      { name: 'sugar', amount: '1 ст.л.' },
      { name: 'salt', amount: 'щепотка' },
    ],
  },
  {
    name: 'toast_with_cheese',
    nameRu: 'Тост с сыром',
    description: 'Хрустящий тост с расплавленным сыром — быстрый завтрак',
    categories: ['BREAKFAST', 'SNACK'],
    cuisine: 'Европейская',
    mealTime: ['breakfast', 'snack'],
    tags: ['быстро', 'вегетарианское'],
    cookTime: 5,
    difficulty: 'easy',
    calories: 280,
    recipe: `## Тост с сыром\n\n1. Поджарить хлеб\n2. Положить сыр сверху\n3. Отправить под гриль на 1-2 минуты\n4. Подавать горячим`,
    ingredients: [
      { name: 'toast_bread', amount: '2 ломтика' },
      { name: 'cheese', amount: '50 г' },
      { name: 'butter', amount: '1 ч.л.' },
    ],
  },
  {
    name: 'bean_soup',
    nameRu: 'Фасолевый суп',
    description: 'Сытный суп из фасоли с овощами',
    categories: ['SOUP'],
    cuisine: 'Средиземноморская',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'суп', 'сытное', 'без глютена'],
    cookTime: 35,
    difficulty: 'easy',
    calories: 220,
    recipe: `## Фасолевый суп\n\n1. Обжарить лук, морковь, чеснок\n2. Добавить фасоль, томаты\n3. Залить водой, варить 25 минут\n4. Посолить, добавить зелень`,
    ingredients: [
      { name: 'canned_beans', amount: '400 г' },
      { name: 'onion', amount: '1 шт' },
      { name: 'carrot', amount: '1 шт' },
      { name: 'garlic', amount: '2 зубчика' },
      { name: 'canned_tomatoes', amount: '400 г' },
      { name: 'olive_oil', amount: '2 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'parsley', amount: 'пучок' },
    ],
  },
  {
    name: 'spinach_omelette',
    nameRu: 'Омлет со шпинатом',
    description: 'Полезный омлет со шпинатом и сыром',
    categories: ['BREAKFAST'],
    cuisine: 'Европейская',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'здоровое', 'без глютена', 'быстро'],
    cookTime: 12,
    difficulty: 'easy',
    calories: 260,
    recipe: `## Омлет со шпинатом\n\n1. Обжарить шпинат с чесноком 2 минуты\n2. Взбить яйца с молоком\n3. Залить шпинат яичной смесью\n4. Посыпать сыром, готовить под крышкой`,
    ingredients: [
      { name: 'chicken_egg', amount: '3 шт' },
      { name: 'spinach', amount: '100 г' },
      { name: 'cheese', amount: '50 г' },
      { name: 'garlic', amount: '1 зубчик' },
      { name: 'butter', amount: '1 ст.л.' },
      { name: 'salt', amount: 'по вкусу' },
    ],
  },
  {
    name: 'pasta_with_tomato',
    nameRu: 'Паста в томатном соусе',
    description: 'Простая и вкусная паста с домашним томатным соусом',
    categories: ['LUNCH', 'DINNER'],
    cuisine: 'Итальянская',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'итальянское', 'быстро'],
    cookTime: 25,
    difficulty: 'easy',
    calories: 380,
    recipe: `## Паста в томатном соусе\n\n1. Отварить пасту\n2. Обжарить чеснок и лук\n3. Добавить томаты, тушить 10 минут\n4. Смешать с пастой, посыпать сыром`,
    ingredients: [
      { name: 'pasta', amount: '200 г' },
      { name: 'canned_tomatoes', amount: '400 г' },
      { name: 'onion', amount: '1 шт' },
      { name: 'garlic', amount: '2 зубчика' },
      { name: 'olive_oil', amount: '2 ст.л.' },
      { name: 'cheese', amount: '50 г' },
      { name: 'salt', amount: 'по вкусу' },
      { name: 'black_pepper', amount: 'по вкусу' },
    ],
  },
]

async function main() {
  console.log('🌱 Starting seed...')

  // Создаём ингредиенты
  console.log('Creating ingredients...')
  const ingredientMap = {}
  for (const ing of ingredients) {
    const { name, nameRu, category, protein = null, fat = null, carbs = null, avgWeightG = null, isBasic = false, emoji = null } = ing
    const data = { name, nameRu, category, protein, fat, carbs, avgWeightG, isBasic, emoji }
    const created = await prisma.ingredient.upsert({
      where: { name },
      update: { nameRu, category, protein, fat, carbs, avgWeightG, isBasic, emoji },
      create: data,
    })
    ingredientMap[ing.name] = created.id
  }
  console.log(`✅ Created ${ingredients.length} ingredients`)

  // Создаём блюда (системные, isPublic: true)
  console.log('Creating dishes...')
  for (const dish of dishes) {
    const { ingredients: dishIngredients, ...dishData } = dish
    const existing = await prisma.dish.findFirst({ where: { name: dish.name } })
    if (existing) {
      console.log(`  ⏭  ${dishData.nameRu} уже есть`)
      continue
    }
    const created = await prisma.dish.create({
      data: {
        ...dishData,
        visibility: 'PUBLIC',
        authorId: null,
        ingredients: {
          create: dishIngredients.map(ing => ({
            ingredientId: ingredientMap[ing.name],
            amount: ing.amount,
            toTaste: ing.amount === 'по вкусу' || ing.amount === 'щепотка',
          })),
        },
      },
    })
    console.log(`  ✅ ${created.nameRu}`)
  }

  console.log(`\n🎉 Seed complete! ${dishes.length} dishes created`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
