const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')
const prisma = new PrismaClient()

const ingredients = [
  { name: 'eggs', nameRu: 'Яйца', category: 'protein', emoji: '🥚' },
  { name: 'milk', nameRu: 'Молоко', category: 'dairy', emoji: '🥛' },
  { name: 'butter', nameRu: 'Сливочное масло', category: 'dairy', emoji: '🧈' },
  { name: 'flour', nameRu: 'Мука', category: 'grain', emoji: '🌾' },
  { name: 'sugar', nameRu: 'Сахар', category: 'pantry', emoji: '🍬' },
  { name: 'salt', nameRu: 'Соль', category: 'spice', emoji: '🧂' },
  { name: 'olive_oil', nameRu: 'Оливковое масло', category: 'oil', emoji: '🫒' },
  { name: 'tomatoes', nameRu: 'Помидоры', category: 'vegetable', emoji: '🍅' },
  { name: 'onion', nameRu: 'Лук', category: 'vegetable', emoji: '🧅' },
  { name: 'garlic', nameRu: 'Чеснок', category: 'vegetable', emoji: '🧄' },
  { name: 'potatoes', nameRu: 'Картофель', category: 'vegetable', emoji: '🥔' },
  { name: 'carrots', nameRu: 'Морковь', category: 'vegetable', emoji: '🥕' },
  { name: 'chicken', nameRu: 'Курица', category: 'meat', emoji: '🍗' },
  { name: 'beef', nameRu: 'Говядина', category: 'meat', emoji: '🥩' },
  { name: 'pasta', nameRu: 'Макароны', category: 'grain', emoji: '🍝' },
  { name: 'rice', nameRu: 'Рис', category: 'grain', emoji: '🍚' },
  { name: 'cheese', nameRu: 'Сыр', category: 'dairy', emoji: '🧀' },
  { name: 'cream', nameRu: 'Сливки', category: 'dairy', emoji: '🥛' },
  { name: 'cucumber', nameRu: 'Огурец', category: 'vegetable', emoji: '🥒' },
  { name: 'bell_pepper', nameRu: 'Болгарский перец', category: 'vegetable', emoji: '🫑' },
  { name: 'mushrooms', nameRu: 'Грибы', category: 'vegetable', emoji: '🍄' },
  { name: 'spinach', nameRu: 'Шпинат', category: 'vegetable', emoji: '🥬' },
  { name: 'oats', nameRu: 'Овсянка', category: 'grain', emoji: '🌾' },
  { name: 'banana', nameRu: 'Банан', category: 'fruit', emoji: '🍌' },
  { name: 'apple', nameRu: 'Яблоко', category: 'fruit', emoji: '🍎' },
  { name: 'lemon', nameRu: 'Лимон', category: 'fruit', emoji: '🍋' },
  { name: 'honey', nameRu: 'Мёд', category: 'pantry', emoji: '🍯' },
  { name: 'sour_cream', nameRu: 'Сметана', category: 'dairy', emoji: '🥛' },
  { name: 'black_pepper', nameRu: 'Чёрный перец', category: 'spice', emoji: '🌶️' },
  { name: 'dill', nameRu: 'Укроп', category: 'herb', emoji: '🌿' },
  { name: 'parsley', nameRu: 'Петрушка', category: 'herb', emoji: '🌿' },
  { name: 'bread', nameRu: 'Хлеб', category: 'grain', emoji: '🍞' },
  { name: 'canned_beans', nameRu: 'Консервированная фасоль', category: 'legume', emoji: '🫘' },
  { name: 'canned_tomatoes', nameRu: 'Консервированные томаты', category: 'pantry', emoji: '🥫' },
  { name: 'soy_sauce', nameRu: 'Соевый соус', category: 'pantry', emoji: '🍶' },
  { name: 'cottage_cheese', nameRu: 'Творог', category: 'dairy', emoji: '🧀' },
  { name: 'semolina', nameRu: 'Манка', category: 'grain', emoji: '🌾' },
]

const dishes = [
  {
    name: 'omelette',
    nameRu: 'Омлет',
    description: 'Классический завтрак — воздушный омлет на сливочном масле',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['быстро', 'вегетарианское', 'без глютена', 'горячее'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 220,
    recipe: `## Омлет классический\n\n**Ингредиенты:**\n- 3 яйца\n- 50 мл молока\n- Соль, перец\n- Сливочное масло\n\n**Приготовление:**\n1. Взбить яйца с молоком, посолить\n2. Растопить масло на сковороде\n3. Вылить смесь, готовить 3-4 минуты\n4. Сложить пополам, подавать горячим`,
    ingredients: ['eggs', 'milk', 'butter', 'salt', 'black_pepper'],
  },
  {
    name: 'omelette_with_tomatoes',
    nameRu: 'Омлет с помидорами',
    description: 'Омлет с сочными помидорами и свежей зеленью',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['быстро', 'вегетарианское', 'без глютена'],
    cookTime: 12,
    difficulty: 'easy',
    calories: 250,
    recipe: `## Омлет с помидорами\n\n**Ингредиенты:**\n- 3 яйца\n- 50 мл молока\n- 1 помидор\n- Укроп\n- Соль, масло\n\n**Приготовление:**\n1. Нарезать помидор кубиками\n2. Взбить яйца с молоком\n3. Обжарить помидоры 1-2 минуты\n4. Залить яичной смесью, готовить до готовности`,
    ingredients: ['eggs', 'milk', 'butter', 'tomatoes', 'salt', 'dill'],
  },
  {
    name: 'scrambled_eggs',
    nameRu: 'Яичница глазунья',
    description: 'Простая яичница — классика завтрака',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['быстро', 'вегетарианское', 'без глютена'],
    cookTime: 7,
    difficulty: 'easy',
    calories: 180,
    recipe: `## Яичница глазунья\n\n1. Разогреть сковороду с маслом\n2. Разбить яйца, посолить\n3. Жарить 3-4 минуты`,
    ingredients: ['eggs', 'butter', 'salt'],
  },
  {
    name: 'oatmeal',
    nameRu: 'Овсяная каша',
    description: 'Питательная овсянка с мёдом и бананом',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'здоровое', 'быстро'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 300,
    recipe: `## Овсяная каша\n\n1. Залить овсянку молоком 1:2\n2. Варить 5-7 минут помешивая\n3. Добавить мёд и банан`,
    ingredients: ['oats', 'milk', 'honey', 'banana'],
  },
  {
    name: 'pancakes',
    nameRu: 'Блины',
    description: 'Тонкие русские блины — к чаю или со сметаной',
    category: 'BREAKFAST',
    mealTime: ['breakfast', 'snack'],
    tags: ['вегетарианское', 'традиционное'],
    cookTime: 30,
    difficulty: 'medium',
    calories: 350,
    recipe: `## Блины\n\n**Ингредиенты:**\n- 2 яйца\n- 500 мл молока\n- 1 стакан муки\n- 1 ст.л. сахара\n- Щепотка соли\n- 2 ст.л. масла\n\n**Приготовление:**\n1. Смешать яйца, молоко, муку, сахар, соль\n2. Добавить масло в тесто\n3. Жарить на горячей сковороде по 1-2 минуты с каждой стороны`,
    ingredients: ['eggs', 'milk', 'flour', 'sugar', 'salt', 'butter'],
  },
  {
    name: 'cottage_cheese_pancakes',
    nameRu: 'Сырники',
    description: 'Творожные сырники — пышные и нежные',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'сытное'],
    cookTime: 25,
    difficulty: 'easy',
    calories: 320,
    recipe: `## Сырники\n\n1. Смешать творог, яйца, муку, сахар, соль\n2. Сформировать лепёшки\n3. Обжарить на масле по 3 минуты с каждой стороны\n4. Подавать со сметаной`,
    ingredients: ['cottage_cheese', 'eggs', 'flour', 'sugar', 'salt', 'butter', 'sour_cream'],
  },
  {
    name: 'chicken_soup',
    nameRu: 'Куриный суп',
    description: 'Наваристый куриный суп с овощами',
    category: 'SOUP',
    mealTime: ['lunch', 'dinner'],
    tags: ['сытное', 'традиционное', 'суп'],
    cookTime: 60,
    difficulty: 'medium',
    calories: 180,
    recipe: `## Куриный суп\n\n1. Отварить курицу 40 минут, снять пену\n2. Добавить нарезанные морковь, лук, картофель\n3. Варить ещё 20 минут\n4. Посолить, добавить зелень`,
    ingredients: ['chicken', 'potatoes', 'carrots', 'onion', 'salt', 'dill', 'parsley'],
  },
  {
    name: 'pasta_carbonara',
    nameRu: 'Паста карбонара',
    description: 'Классическая итальянская паста в сливочно-яичном соусе',
    category: 'LUNCH',
    mealTime: ['lunch', 'dinner'],
    tags: ['итальянское', 'сытное', 'быстро'],
    cookTime: 20,
    difficulty: 'medium',
    calories: 520,
    recipe: `## Паста карбонара\n\n1. Отварить пасту al dente\n2. Смешать яйца, тёртый сыр, перец\n3. Обжарить бекон (опционально)\n4. Смешать горячую пасту с яичной смесью\n5. Подавать сразу`,
    ingredients: ['pasta', 'eggs', 'cheese', 'cream', 'black_pepper', 'salt', 'butter'],
  },
  {
    name: 'fried_potatoes',
    nameRu: 'Жареная картошка',
    description: 'Хрустящая жареная картошка с луком',
    category: 'LUNCH',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'сытное', 'быстро', 'традиционное'],
    cookTime: 25,
    difficulty: 'easy',
    calories: 380,
    recipe: `## Жареная картошка\n\n1. Нарезать картофель ломтиками\n2. Разогреть масло на сковороде\n3. Жарить 15-20 минут, перемешивая\n4. Добавить лук, жарить ещё 5 минут\n5. Посолить, добавить укроп`,
    ingredients: ['potatoes', 'onion', 'olive_oil', 'salt', 'dill'],
  },
  {
    name: 'rice_with_vegetables',
    nameRu: 'Рис с овощами',
    description: 'Лёгкий рис с болгарским перцем и морковью',
    category: 'LUNCH',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'здоровое', 'без глютена'],
    cookTime: 30,
    difficulty: 'easy',
    calories: 280,
    recipe: `## Рис с овощами\n\n1. Промыть и отварить рис\n2. Нарезать морковь, перец, лук\n3. Обжарить овощи 7-10 минут\n4. Смешать с рисом, посолить`,
    ingredients: ['rice', 'carrots', 'bell_pepper', 'onion', 'olive_oil', 'salt'],
  },
  {
    name: 'greek_salad',
    nameRu: 'Греческий салат',
    description: 'Свежий средиземноморский салат с сыром',
    category: 'SALAD',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'без глютена', 'свежее', 'быстро'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 220,
    recipe: `## Греческий салат\n\n1. Нарезать помидоры, огурцы, перец\n2. Добавить сыр фета кубиками\n3. Заправить оливковым маслом и лимоном\n4. Посолить, поперчить`,
    ingredients: ['tomatoes', 'cucumber', 'bell_pepper', 'cheese', 'olive_oil', 'lemon', 'salt'],
  },
  {
    name: 'mushroom_soup',
    nameRu: 'Грибной суп',
    description: 'Ароматный суп с лесными грибами',
    category: 'SOUP',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'суп', 'ароматное'],
    cookTime: 40,
    difficulty: 'easy',
    calories: 150,
    recipe: `## Грибной суп\n\n1. Обжарить грибы с луком\n2. Добавить нарезанный картофель\n3. Залить водой, варить 25 минут\n4. Добавить сметану, зелень`,
    ingredients: ['mushrooms', 'potatoes', 'onion', 'sour_cream', 'butter', 'salt', 'dill'],
  },
  {
    name: 'beef_stew',
    nameRu: 'Тушёная говядина с овощами',
    description: 'Нежная говядина в томатном соусе',
    category: 'DINNER',
    mealTime: ['dinner'],
    tags: ['сытное', 'традиционное'],
    cookTime: 90,
    difficulty: 'medium',
    calories: 420,
    recipe: `## Тушёная говядина\n\n1. Обжарить говядину кусочками\n2. Добавить лук, морковь\n3. Добавить томаты, тушить 60-70 минут\n4. Посолить, поперчить`,
    ingredients: ['beef', 'onion', 'carrots', 'canned_tomatoes', 'garlic', 'olive_oil', 'salt', 'black_pepper'],
  },
  {
    name: 'vegetable_stir_fry',
    nameRu: 'Жаркое из овощей',
    description: 'Быстрое жаркое с соевым соусом по-азиатски',
    category: 'LUNCH',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'азиатское', 'быстро', 'здоровое'],
    cookTime: 15,
    difficulty: 'easy',
    calories: 200,
    recipe: `## Жаркое из овощей\n\n1. Нарезать все овощи соломкой\n2. Обжарить на сильном огне 5-7 минут\n3. Добавить соевый соус, чеснок\n4. Подавать с рисом`,
    ingredients: ['bell_pepper', 'carrots', 'mushrooms', 'onion', 'garlic', 'soy_sauce', 'olive_oil'],
  },
  {
    name: 'chicken_with_rice',
    nameRu: 'Курица с рисом',
    description: 'Запечённая курица с рассыпчатым рисом',
    category: 'DINNER',
    mealTime: ['lunch', 'dinner'],
    tags: ['сытное', 'традиционное', 'без глютена'],
    cookTime: 50,
    difficulty: 'easy',
    calories: 450,
    recipe: `## Курица с рисом\n\n1. Замариновать курицу с чесноком и специями\n2. Обжарить до золотистой корочки\n3. Отварить рис\n4. Подавать вместе`,
    ingredients: ['chicken', 'rice', 'garlic', 'olive_oil', 'salt', 'black_pepper'],
  },
  {
    name: 'semolina_porridge',
    nameRu: 'Манная каша',
    description: 'Нежная манная каша с маслом',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'нежное', 'традиционное'],
    cookTime: 10,
    difficulty: 'easy',
    calories: 260,
    recipe: `## Манная каша\n\n1. Вскипятить молоко\n2. Всыпать манку тонкой струйкой, помешивая\n3. Варить 5 минут\n4. Добавить масло, сахар по вкусу`,
    ingredients: ['semolina', 'milk', 'butter', 'sugar', 'salt'],
  },
  {
    name: 'toast_with_cheese',
    nameRu: 'Тост с сыром',
    description: 'Хрустящий тост с расплавленным сыром — быстрый завтрак',
    category: 'BREAKFAST',
    mealTime: ['breakfast', 'snack'],
    tags: ['быстро', 'вегетарианское'],
    cookTime: 5,
    difficulty: 'easy',
    calories: 280,
    recipe: `## Тост с сыром\n\n1. Поджарить хлеб\n2. Положить сыр сверху\n3. Отправить под гриль на 1-2 минуты\n4. Подавать горячим`,
    ingredients: ['bread', 'cheese', 'butter'],
  },
  {
    name: 'bean_soup',
    nameRu: 'Фасолевый суп',
    description: 'Сытный суп из фасоли с овощами',
    category: 'SOUP',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'суп', 'сытное', 'без глютена'],
    cookTime: 35,
    difficulty: 'easy',
    calories: 220,
    recipe: `## Фасолевый суп\n\n1. Обжарить лук, морковь, чеснок\n2. Добавить фасоль, томаты\n3. Залить водой, варить 25 минут\n4. Посолить, добавить зелень`,
    ingredients: ['canned_beans', 'onion', 'carrots', 'garlic', 'canned_tomatoes', 'olive_oil', 'salt', 'parsley'],
  },
  {
    name: 'spinach_omelette',
    nameRu: 'Омлет со шпинатом',
    description: 'Полезный омлет со шпинатом и сыром',
    category: 'BREAKFAST',
    mealTime: ['breakfast'],
    tags: ['вегетарианское', 'здоровое', 'без глютена', 'быстро'],
    cookTime: 12,
    difficulty: 'easy',
    calories: 260,
    recipe: `## Омлет со шпинатом\n\n1. Обжарить шпинат с чесноком 2 минуты\n2. Взбить яйца с молоком\n3. Залить шпинат яичной смесью\n4. Посыпать сыром, готовить под крышкой`,
    ingredients: ['eggs', 'spinach', 'cheese', 'garlic', 'butter', 'salt'],
  },
  {
    name: 'pasta_with_tomato',
    nameRu: 'Паста в томатном соусе',
    description: 'Простая и вкусная паста с домашним томатным соусом',
    category: 'LUNCH',
    mealTime: ['lunch', 'dinner'],
    tags: ['вегетарианское', 'итальянское', 'быстро'],
    cookTime: 25,
    difficulty: 'easy',
    calories: 380,
    recipe: `## Паста в томатном соусе\n\n1. Отварить пасту\n2. Обжарить чеснок и лук\n3. Добавить томаты, тушить 10 минут\n4. Смешать с пастой, посыпать сыром`,
    ingredients: ['pasta', 'canned_tomatoes', 'onion', 'garlic', 'olive_oil', 'cheese', 'salt', 'black_pepper'],
  },
]

async function main() {
  console.log('🌱 Starting seed...')

  // Create ingredients
  console.log('Creating ingredients...')
  const ingredientMap = {}
  for (const ing of ingredients) {
    const created = await prisma.ingredient.upsert({
      where: { name: ing.name },
      update: {},
      create: ing,
    })
    ingredientMap[ing.name] = created.id
  }
  console.log(`✅ Created ${ingredients.length} ingredients`)

  // Create dishes
  console.log('Creating dishes...')
  for (const dish of dishes) {
    const { ingredients: dishIngredients, ...dishData } = dish
    const existing = await prisma.dish.findFirst({ where: { name: dish.name } })
    if (existing) {
      console.log(`  ⏭  ${dishData.nameRu} уже есть`)
      continue
    }
    const created = await prisma.dish.create({
      data: {
        ...dishData,
        ingredients: {
          create: dishIngredients.map(ingName => ({
            ingredientId: ingredientMap[ingName],
          })),
        },
      },
    })
    console.log(`  ✅ ${created.nameRu}`)
  }

  console.log(`\n🎉 Seed complete! ${dishes.length} dishes created`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
